[canary]
smartcity-vm01 ansible_host=127.0.0.1 ansible_port=12221

[production]
smartcity-vm02 ansible_host=127.0.0.1 ansible_port=12222
smartcity-vm03 ansible_host=127.0.0.1 ansible_port=12223

[smartcity:children]
canary
production

[smartcity:vars]
ansible_user=ansible
ansible_password={{ lookup("env", "ANSIBLE_PASSWORD") }}
ansible_become=true
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
